# need 4 gpus
# max_new_tokens still hardcoded at 64 inside run_smol.py

project: coconut
save_path: /share/sds/vc383/scratch_coconut/smol135-gsm-cot/checkpoints
name: smol135-gsm-cot

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: HuggingFaceTB/SmolLM-135M
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False
batch_size_training: 32
debug: False
gradient_accumulation_steps: 1
num_epochs: 25
lr: !!float "1e-4"
weight_decay: 0.01
